
random_state: 42
model_name: "transformer"
processing: "baseline"
dataset: "baseline"


# Testing
test_batch_size: 256

# Training
pretrained: 1 # True
device: "cuda"
model_name_or_path: 'distilbert-base-uncased'
md_max_len: 128
total_max_len: 128
accumulation_steps: 4
batch_size: 128
n_workers: 6
epochs: 5
num_selected_code_cells: 20
num_notebooks: 5000


